name: Signagelive
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7596
title: Digital Signage Software as a Service Platform
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#503d2b'
    - '#beb098'
    - '#dfeefb'
    - '#e54a34'
    - '#3f78d2'
  brandStrength: 0.5608858042396605
  lightness: 0.21832311432808638
  saturation: 0.5680747954174876
  rhythmicContrast: 0.75
purpose: []
