name: signagelive
favicon: null
layout_spectrum: 0.9119404905941337
typography_spectrum: 0.7573125201743096
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5608858042396605
  lightness: 0.21832311432808638
  saturation: 0.5680747954174876
  rhythmicContrast: 0.394080986501649
purpose: []
